# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-02 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180202_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='img',
        ),
        migrations.AddField(
            model_name='articles',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
    ]
